version: '3.4'

services:
  mtproto:
    restart: always
    container_name: "tuktuk-mtproto"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'

networks:
  default:
    name: external-network
    external: true